services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd  # Replace with a strong password
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/home/shaharyar/git-repos/docker-containers/db/mssql

volumes:
  mssql_data:
