version: "3.8"

services:
# flask app 
  flask: 
   container_name: flask-app 
   build:
      context: .
   environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
   ports:
      - "5000:5000"
   networks:
      - flask-net
   depends_on:
    - mysql
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # SQL Server    
  mysql: 
    container_name: my_sql
    image: mysql
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - flask-net
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s 

# Volumes && network 

volumes:
  mysql-data:
networks:
  flask-net:
   driver: bridge

