apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  containers:
    - name: stress-test
      image: polinux/stress
      resources:
        requests:
          memory: "50Mi"
        limits:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "85M", "--timeout", "10s"]
