services:
  postgres:
    image: docker.io/postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnet
    restart: unless-stopped

  pgadmin:
    image: docker.io/dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - pgnet
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:

networks:
  pgnet:

