
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password  # Replace with a root password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/home/shaharyar/git-repos/dockker-containers/db/mysql

volumes:
  mysql_data:
