apiVersion: v1
kind: Pod
metadata:
  name: express-app
  labels:
    app: express-app
spec:
  containers:
    - image: shaharyarshakir/express-app
      name: express-app
      resources:
        requests:
          cpu: 200m
        limits:
          cpu: 500m
      ports:
        - containerPort: 3000
