services:
  minio:
    image: docker.io/bitnami/minio:2025
    container_name: minio-server
    ports:
      - '9000:9000' # MinIO API
      - '9001:9001' # MinIO Console
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootpassword
      - BITNAMI_DEBUG=true
volumes:
  minio_data:
