apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base

nameSuffix: -dev
namePrefix: app-1-

labels:
  - pairs:
      env: dev
    includeSelectors: true

images:
- name: nginx
  newName: nginx
  newTag: "latest"
commonAnnotations:
      branch: dev
      support: 800-800
namespace: dev
replicas:
  - name: nginx-deployment
    count: 2
