---
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge_data:/app/data
    environment:
      DOCKGE_STACKS_DIR: /app/data/stacks
    restart: unless-stopped

volumes:
  dockge_data:
