Vagrant.configure("2") do |config|
  # Global hostmanager config
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # Control Node - AlmaLinux 9
  config.vm.define "control" do |control|
    control.vm.box = "generic/alma9"
    control.vm.hostname = "control"
    control.vm.network "private_network", ip: "192.168.56.100"

    # Rsync shared folder
    control.vm.synced_folder "./ansible", "/home/vagrant/ansible", type: "rsync",
      rsync__exclude: [".git/", "node_modules/", "*.log"],
      rsync__auto: true

    control.vm.provider "virtualbox" do |vb|
      vb.name = "control"
      vb.memory = 1024
      vb.cpus = 1
    end

    control.hostmanager.aliases = ["control.local"]
  end

  # Nodes definition
  nodes = [
    { name: "node1", ip: "192.168.56.101", box: "generic/rocky9" },
    { name: "node2", ip: "192.168.56.102", box: "ubuntu/jammy64" },
    { name: "node3", ip: "192.168.56.103", box: "ubuntu/focal64" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.box = node[:box]
      n.vm.hostname = node[:name]
      n.vm.network "private_network", ip: node[:ip]

      n.vm.provider "virtualbox" do |vb|
        vb.name = node[:name]
        vb.memory = 1024
        vb.cpus = 1
      end

      # Enable password auth via shell script
      n.vm.provision "shell", path: "scripts/enable_passauth.sh"
      n.hostmanager.aliases = ["#{node[:name]}.local"]
    end
  end
end
