kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
metadata: 
  name: kind-kind-cluster-yt
nodes:
   - role: control-plane
     image: kindest/node:v1.32.2
   - role: worker
     image: kindest/node:v1.32.2
   - role: worker
     image: kindest/node:v1.32.2
   - role: worker
     image: kindest/node:v1.32.2
     extraPortMappings:
     - containerPort: 80
       hostPort: 8080
       protocol: tcp
     - containerPort: 443
       hostPort: 444
       protocol: tcp
