apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../../base

nameSuffix: -prod
namePrefix: app-1-

labels:
  - pairs:
      env: prod
    includeSelectors: true

images:
- name: nginx
  newName: nginx
  newTag: "1.24"
commonAnnotations:
      branch: prod
      support: 800-800
namespace: prod
replicas:
  - name: nginx-deployment
    count: 4
