---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache httpd 
      yum:
         name: httpd
         state: present
    - name: Start & Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        backup: yes


