- name: Advanced demo
  hosts: all
  become: yes
  tasks:
    - name: Install multiple packages only if RedHat
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - wget
      when: ansible_os_family == "RedHat"
      notify: Restart Network

  handlers:
    - name: Restart Network
      service:
        name: network
        state: restarted
