services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # ⚠️ Stacks Directory: Must match EXACTLY on both sides, and be FULL path
      - /home/shaharyar/git-repos/docker-containers:/home/shaharyar/git-repos/docker-containers
    environment:
      - DOCKGE_STACKS_DIR=/home/shaharyar/git-repos/docker-containers

