Vagrant.configure("2") do |config|
    config.vm.define "scriptbox" do |scriptbox|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.41"
    end
  
    config.vm.define "web01" do |web01|
      web02.vm.box = "centos/7"
      web02.vm.hostname = "web01"
      web02.vm.network "private_network", ip: "192.168.56.41"
    end
  
    config.vm.define "web02" do |web02|
        web03.vm.box = "centos/7"
        web03.vm.hostname = "web02"
        web03.vm.network "private_network", ip: "192.168.56.44"
      end

   
  end
  